name: effective-solar
channels:
  - defaults
dependencies:
  - pip=21.*
  - python=3.8.0
  - pip:
    - matplotlib==3.5.1
    - numpy==1.22.3
    - pandas==1.4.2
    - prophet==1.1
    - pvlib==0.9.1
    - scikit-learn==1.0.2
    - sklearn==0.0
    - protobuf==3.20.1
    - tensorflow==2.8.0
    - keras==2.8
    - holidays==0.24